const NOW=new Date("2026-09-20T09:16:00-05:00");
const TABS=[["week","This week"],["month","This month"],["lookback","Year lookback"],["catalog","Catalog"],["claims","Claims"],["versions","Versions"],["reviews","Reviews"],["ledger","Ledger"],["pillars","Pillars"],["feeds","Feeds"],["runs","Daily runs"]];
let DATA={papers:[],pillars:[],fields:[],feeds:[],runs:[]};
let CLAIMS={claims:[],axes:{}};
let VERSIONS={history:[],buses:[],milestones:[],lines:[],current:{}};
let REVIEWS={cards:[]};
let LEDGER={};
let tab="week",field="all",q="",sort="importance";
const KEY="dbe-observatory-overlay-v1";
let FREEZE={actions:[],dbe:"DBE-0.1.2",dbes:"DBES-0.1.2"};
const idea=p=>p.coreIdea||p.plain||"";
const fieldLabel=id=>(DATA.fields.find(f=>f.id===id||f===id)||{}).short||id;
function inWeek(p){const t=new Date(p.date||p.year+"-01-01").getTime();return NOW-t<=7*864e5||p.role==="week"}
function inMonth(p){return String(p.date||"").startsWith("2026-09")||String(p.date||"").startsWith("2026-08")||p.role==="month"||inWeek(p)}
function inLookback(p){return String(p.date||"")>="2025-09-20"||["lookback","week","month"].includes(p.role)}
function roleLabel(p){if(p.role==="internal")return"Program source";if(p.foundational||p.role==="pillar")return"Foundational";if(inWeek(p)||p.role==="week")return"This week";if(inMonth(p))return"This month";if(inLookback(p))return"Year lookback";return p.role||"Catalog"}
function statusClass(s){s=String(s||"").toUpperCase();if(["KEEP","PASS","INCLUDE","STRENGTHEN"].includes(s))return"keep";if(["CUT","REJECT","DISCONFIRM"].includes(s))return"cut";if(["HOLD","QUEUE","WATCH","WEAKEN","NEW PILLAR"].includes(s))return"warn";return"acc"}
function loadFreeze(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"null");if(raw&&raw.dbe)return raw}catch(e){}return{actions:[],dbe:(VERSIONS.current||{}).DBE||"DBE-0.1.2",dbes:(VERSIONS.current||{}).DBES||"DBES-0.1.2"}}
function saveFreeze(){localStorage.setItem(KEY,JSON.stringify(FREEZE))}
function bump(v,kind){const m=String(v).match(/^(DBE|DBES)-(\d+)\.(\d+)\.(\d+)$/);if(!m)return v;return kind==="patch"?m[1]+"-"+m[2]+"."+m[3]+"."+(+m[4]+1):m[1]+"-"+m[2]+"."+(+m[3]+1)+".0"}
function toast(msg){document.querySelectorAll(".toast").forEach(n=>n.remove());const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}
function applied(id){return FREEZE.actions.some(a=>a.reviewId===id)}
function applyCard(id){const c=(REVIEWS.cards||[]).find(x=>x.id===id);if(!c)return;if(applied(id)){toast("Already applied to the working freeze.");return}const line=(c.bind||[]).some(b=>String(b).startsWith("S-"))?"dbes":"dbe";if(c.action==="NEW PILLAR"||c.action==="REJECT"||c.route==="QUEUE"){FREEZE.actions.push({reviewId:id,action:c.action,at:new Date().toISOString()});saveFreeze();toast("Queued "+c.action+" — no auto-bump");paintFreeze();render();return}if(c.action==="INCLUDE")FREEZE[line]=bump(FREEZE[line],"patch");if(["WEAKEN","DISCONFIRM","STRENGTHEN"].includes(c.action))FREEZE[line]=bump(FREEZE[line],"minor");FREEZE.actions.push({reviewId:id,action:c.action,at:new Date().toISOString()});saveFreeze();toast("Applied "+c.action+" → "+FREEZE.dbe+" / "+FREEZE.dbes);paintFreeze();render()}
function resetFreeze(){FREEZE={actions:[],dbe:(VERSIONS.current||{}).DBE||"DBE-0.1.2",dbes:(VERSIONS.current||{}).DBES||"DBES-0.1.2"};saveFreeze();toast("Working freeze reset to published current");paintFreeze();render()}
function paintFreeze(){const el=document.getElementById("freezeBar");if(!el)return;el.innerHTML="<code>"+FREEZE.dbe+"</code><span>/</span><code>"+FREEZE.dbes+"</code><span> "+FREEZE.actions.length+" local action"+(FREEZE.actions.length===1?"":"s")+"</span><button class=\"ghost\" type=\"button\" id=\"resetFreeze\">Reset freeze</button>";document.getElementById("resetFreeze").onclick=resetFreeze;const stats=document.getElementById("stats");if(stats){const papers=DATA.papers||[];stats.innerHTML=[["Sources",papers.length],["Claims",(CLAIMS.claims||[]).length],["DBE",FREEZE.dbe.replace("DBE-","")],["DBE-S",FREEZE.dbes.replace("DBES-","")]].map(kv=>"<div class=\"stat\"><dt>"+kv[0]+"</dt><dd>"+kv[1]+"</dd></div>").join("")}}
function meters(p){const row=(label,n)=>"<div><div class=\"lbl\"><span>"+label+"</span><span>"+n+"</span></div><div class=\"bar\"><i style=\"width:"+Math.max(4,Math.min(100,n||0))+"%\"></i></div></div>";return "<div class=\"meters\">"+row("Importance",p.importance)+row("Confidence",p.confidence)+row("Popularity",p.popularity)+"</div>"}
function pool(){let papers=DATA.papers.slice();if(tab==="week")papers=papers.filter(p=>inWeek(p)||p.role==="week");else if(tab==="month")papers=papers.filter(inMonth);else if(tab==="lookback")papers=papers.filter(inLookback);else if(tab==="pillars")papers=papers.filter(p=>p.foundational||p.role==="pillar"||p.role==="internal");if(field!=="all")papers=papers.filter(p=>(p.fields||[]).includes(field));if(q){const s=q.toLowerCase();papers=papers.filter(p=>JSON.stringify(p).toLowerCase().includes(s))}papers.sort((a,b)=>sort==="date"?String(b.date).localeCompare(String(a.date)):(b[sort]||0)-(a[sort]||0));return papers}
function openPaper(id){const p=DATA.papers.find(x=>x.id===id);if(!p)return;const pillar=(DATA.pillars||[]).find(x=>x.id===p.pillarId||x.id===p.suggestedPillar);const claims=(CLAIMS.claims||[]).filter(c=>(p.claimIds||[]).includes(c.id));const overlay=document.createElement("div");overlay.className="overlay";overlay.innerHTML="<article class=\"panel\"><p class=\"kicker\">"+(p.source||"")+"</p><h2>"+p.title+"</h2><p class=\"meta\">"+[].concat(p.authors||[]).join(", ")+" · "+(p.year||"")+" · "+(p.venue||"")+"</p><div>"+(p.fields||[]).map(f=>"<span class=\"tag\">"+fieldLabel(f)+"</span>").join("")+(p.claimIds||[]).map(t=>"<span class=\"tag acc\">"+t+"</span>").join("")+"</div>"+meters(p)+"<p class=\"meta\" style=\"margin-top:0.75rem\">Harvest gauges are not C/T/D/A and cannot raise a claim.</p><p><b>Core idea.</b> "+idea(p)+"</p><p><b>Why it matters.</b> "+(p.whyItMatters||"")+"</p><p><b>One limitation.</b> "+(p.limitation||"")+"</p>"+claims.map(c=>"<p class=\"legend\"><span class=\"tag "+statusClass(c.status)+"\">"+c.status+"</span> <b>"+c.id+"</b> "+c.C+" "+c.T+" "+c.D+" "+c.A+"<br/>"+c.verdict+"</p>").join("")+(pillar?"<p class=\"legend\"><b>"+(pillar.engineStatus||pillar.status)+": "+pillar.name+"</b><br/>"+(pillar.engineNote||pillar.dbeGoal||"")+"</p>":"")+"<div class=\"actions\">"+(p.url&&String(p.url).startsWith("http")?"<a href=\""+p.url+"\" target=\"_blank\" rel=\"noreferrer\">Open source</a>":"")+"<button class=\"ghost\" type=\"button\">Close</button></div></article>";overlay.addEventListener("click",e=>{if(e.target===overlay||e.target.closest(".ghost"))overlay.remove()});document.body.appendChild(overlay)}
function paperRow(p){return "<button class=\"row\" data-id=\""+p.id+"\"><div><div>"+(p.foundational?"<span class=\"tag acc\">Foundational</span>":"<span class=\"tag\">"+roleLabel(p)+"</span>")+(p.claimIds||[]).map(id=>"<span class=\"tag acc\">"+id+"</span>").join("")+"<span class=\"meta\"> "+(p.date||p.year||"")+"</span></div><h3>"+p.title+"</h3><p class=\"meta\">"+[].concat(p.authors||[]).slice(0,4).join(", ")+" · "+(p.venue||"")+"</p><p>"+idea(p)+"</p><div>"+(p.fields||[]).map(f=>"<span class=\"tag\">"+fieldLabel(f)+"</span>").join("")+"</div></div>"+meters(p)+"</button>"}
function renderClaims(){const groups={DBE:[],"DBE-S":[]};(CLAIMS.claims||[]).forEach(c=>(groups[c.doc]||(groups[c.doc]=[])).push(c));return Object.entries(groups).map(([doc,list])=>"<h2>"+doc+"</h2><div class=\"grid\">"+list.map(c=>"<article class=\"card\"><div style=\"display:flex;justify-content:space-between;gap:0.75rem\"><div><span class=\"tiny\">"+c.id+"</span><h3>"+c.name+"</h3><p class=\"meta\">"+c.claim+"</p></div><span class=\"tag "+statusClass(c.status)+"\">"+c.status+"</span></div><div class=\"axes\">"+["C","T","D","A"].map(k=>"<div><div class=\"tiny\">"+k+"</div>"+c[k]+"</div>").join("")+"</div><p>"+c.verdict+"</p><p class=\"meta\"><b>Disputer.</b> "+c.disputer+"</p><p class=\"meta\"><b>Kill.</b> "+c.kill+"</p><div>"+(c.evidence||[]).map(id=>"<button class=\"chip\" data-open=\""+id+"\">"+id+"</button>").join("")+"</div></article>").join("")+"</div>").join("")}
function renderVersions(){const lines=(VERSIONS.lines||[]).map(l=>"<article class=\"card\"><div class=\"tiny\">"+l.id+"</div><h3>"+l.name+"</h3><p class=\"kicker\">"+l.current+"</p><p>"+l.freeze+"</p></article>").join("");const buses=(VERSIONS.buses||[]).map(b=>"<article class=\"card\"><h3>Bus "+b.id+" · "+b.name+"</h3><p class=\"tiny\">"+b.C+" · "+b.D+"</p><p>"+b.target+"</p><p class=\"meta\">"+b.interface+"</p></article>").join("");const hist=(VERSIONS.history||[]).map(v=>"<article class=\"card\"><span class=\"tag acc\">"+v.kind+"</span> <span class=\"tag\">"+v.action+"</span><h3>"+v.version+" · "+v.title+"</h3><p class=\"meta\">"+v.date+"</p><p>"+v.summary+"</p><div class=\"axes\">"+Object.entries(v.claimSnapshot||{}).map(([k,val])=>"<div><div class=\"tiny\">"+k+"</div>"+val+"</div>").join("")+"</div></article>").join("");return "<div class=\"grid\">"+lines+"</div><h2>Buses</h2><div class=\"grid\">"+buses+"</div><h2>Version log</h2>"+hist}
function renderReviews(){return (REVIEWS.cards||[]).map(c=>"<article class=\"card\"><span class=\"tag "+statusClass(c.action)+"\">"+c.action+"</span> <span class=\"tag\">"+c.route+"</span> "+(c.bind||[]).map(id=>"<span class=\"tag acc\">"+id+"</span>").join("")+"<h3>"+((DATA.papers.find(p=>p.id===c.paperId)||{}).title||c.paperId)+"</h3><p>"+(c.plain&&c.plain.core||"")+"</p><p class=\"meta\"><b>Why.</b> "+(c.plain&&c.plain.why||"")+"</p><p class=\"meta\"><b>Limitation.</b> "+(c.plain&&c.plain.limit||"")+"</p><p class=\"meta\"><b>Disputer.</b> "+c.disputer+"</p><p class=\"tiny\">"+c.claimDelta+" · "+(c.version||"no version")+"</p><div class=\"actions\"><button class=\"chip\" data-open=\""+c.paperId+"\">Open paper</button><button class=\"chip apply\" data-apply=\""+c.id+"\" "+(applied(c.id)?"disabled":"")+">"+(applied(c.id)?"Applied":"APPLY "+c.action)+"</button></div></article>").join("")}
function renderLedger(){const defs=(LEDGER.definitions||[]).map(d=>"<article class=\"card\"><div class=\"tiny\">"+d.id+"</div><h3>"+d.name+"</h3><p class=\"meta\">"+d.meaning+"</p><p>"+d.current+"</p></article>").join("");const terms=(LEDGER.terms||[]).map(t=>"<article class=\"card\"><b>"+t.id+"</b> "+t.name+"<p class=\"meta\">"+t.note+"</p></article>").join("");return "<p class=\"lede\">"+(LEDGER.northStar||"")+"</p><div class=\"grid\">"+defs+"</div><h2>Required terms</h2>"+terms}
function renderFeeds(){const feeds=(DATA.feeds||[]).map(f=>"<article class=\"card\"><h3>"+f.label+"</h3><p class=\"meta\">"+f.id+"</p><div class=\"actions\"><a href=\""+f.url+"\" target=\"_blank\" rel=\"noreferrer\">Open feed</a></div></article>").join("");const fields=(DATA.fields||[]).map(f=>"<article class=\"card\"><div class=\"tiny\">"+f.id+"</div><h3>"+f.label+"</h3><p>"+(f.goal||"")+"</p><p class=\"meta\">"+(f.feed||"")+"</p></article>").join("");return "<h2>Live feeds</h2><div class=\"grid\">"+feeds+"</div><h2>Field goals</h2><div class=\"grid\">"+fields+"</div>"}
function renderPillars(only){const list=(DATA.pillars||[]).filter(p=>{const on=["KEEP","WATCH","HOLD","CUT"].includes(p.engineStatus);return only==="queue"?!on:on});return "<div class=\"grid\">"+list.map(p=>"<article class=\"card\"><div style=\"display:flex;justify-content:space-between;gap:0.75rem\"><h3>"+p.name+"</h3><span class=\"tag "+statusClass(p.engineStatus||p.status)+"\">"+(p.engineStatus||p.status)+"</span></div><p>"+(p.statement||"")+"</p><p class=\"meta\">"+(p.engineNote||p.dbeGoal||"")+"</p><div>"+(p.evidence||[]).map(id=>"<button class=\"chip\" data-open=\""+id+"\">"+id+"</button>").join("")+"</div></article>").join("")+"</div>"}
function render(){const main=document.getElementById("main");const tools=document.getElementById("tools");const chips=document.getElementById("chips");const hideTools=["claims","versions","reviews","ledger","pillars","feeds","runs"].includes(tab);tools.style.display=hideTools?"none":"flex";chips.style.display=hideTools?"none":"flex";if(tab==="claims")main.innerHTML=renderClaims();else if(tab==="versions")main.innerHTML=renderVersions();else if(tab==="reviews")main.innerHTML=renderReviews();else if(tab==="ledger")main.innerHTML=renderLedger();else if(tab==="pillars")main.innerHTML="<h2>Engine</h2>"+renderPillars("engine")+"<h2>Queued</h2>"+renderPillars("queue");else if(tab==="feeds")main.innerHTML=renderFeeds();else if(tab==="runs"){const feeds=(DATA.feeds||[]).map(f=>"<li class=\"meta\" style=\"display:flex;justify-content:space-between;padding:0.6rem 0;border-bottom:1px solid var(--border)\"><span>"+(f.label||f)+"</span><a href=\""+(f.url||f)+"\">"+String(f.url||f).replace("https://","")+"</a></li>").join("");const runs=(DATA.runs||[]).map(r=>"<div class=\"run\"><span class=\"tag acc\">"+r.kind+"</span> <span class=\"meta\">"+(r.startedAt||"")+"</span><p>"+(r.notes||"")+"</p></div>").join("");main.innerHTML="<h2>Feeds</h2><ul style=\"list-style:none;padding:0\">"+feeds+"</ul><h2>Ingest runs</h2>"+runs}else{const papers=pool();main.innerHTML=papers.length?"<div class=\"list\">"+papers.map(paperRow).join("")+"</div>":"<p class=\"empty\">No papers in this slice.</p>"}main.querySelectorAll("[data-id], [data-open]").forEach(btn=>btn.addEventListener("click",()=>openPaper(btn.dataset.id||btn.dataset.open)));main.querySelectorAll("[data-apply]").forEach(btn=>btn.addEventListener("click",()=>applyCard(btn.dataset.apply)))}
function setup(){const papers=DATA.papers||[];document.getElementById("stats").innerHTML=[["Sources",papers.length],["Claims",(CLAIMS.claims||[]).length],["DBE",FREEZE.dbe.replace("DBE-","")],["DBE-S",FREEZE.dbes.replace("DBES-","")]].map(kv=>"<div class=\"stat\"><dt>"+kv[0]+"</dt><dd>"+kv[1]+"</dd></div>").join("");paintFreeze();document.getElementById("tabs").innerHTML=TABS.map(([id,label])=>"<button data-tab=\""+id+"\" class=\""+(id===tab?"active":"")+"\">"+label+"</button>").join("");const counts={};papers.forEach(p=>(p.fields||[]).forEach(f=>counts[f]=(counts[f]||0)+1));document.getElementById("chips").innerHTML="<button class=\"chip "+(field==="all"?"active":"")+"\" data-field=\"all\">All fields<span>"+papers.length+"</span></button>"+DATA.fields.map(f=>"<button class=\"chip "+(field===f.id?"active":"")+"\" data-field=\""+f.id+"\">"+f.short+"<span>"+(counts[f.id]||0)+"</span></button>").join("");document.getElementById("tabs").onclick=e=>{const b=e.target.closest("[data-tab]");if(!b)return;tab=b.dataset.tab;[...document.getElementById("tabs").children].forEach(x=>x.classList.toggle("active",x===b));render()};document.getElementById("chips").onclick=e=>{const b=e.target.closest("[data-field]");if(!b)return;field=b.dataset.field;[...document.getElementById("chips").children].forEach(x=>x.classList.toggle("active",x===b));const meta=DATA.fields.find(f=>f.id===field);const g=document.getElementById("goal");if(meta&&meta.goal){g.hidden=false;g.innerHTML="<b>"+meta.label+".</b> "+meta.goal}else g.hidden=true;render()};document.getElementById("q").oninput=e=>{q=e.target.value;render()};document.getElementById("sort").onchange=e=>{sort=e.target.value;render()};render()}
Promise.all([fetch("catalog.json").then(r=>r.json()),fetch("claims.json").then(r=>r.json()).catch(()=>({claims:[]})),fetch("versions.json").then(r=>r.json()).catch(()=>({history:[]})),fetch("reviews.json").then(r=>r.json()).catch(()=>({cards:[]})),fetch("ledger.json").then(r=>r.json()).catch(()=>({}))]).then(([cat,claims,versions,reviews,ledger])=>{DATA=cat;CLAIMS=claims;VERSIONS=versions;REVIEWS=reviews;LEDGER=ledger;FREEZE=loadFreeze();setup()}).catch(()=>{document.getElementById("main").innerHTML="<p class='empty'>Serve this folder so catalog.json can load.</p>"});
